tuzig/terminal7

src/css/terminal7.css, src/window.js, www/index.html
From #122
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#122: Tab names should be edited in a modal](https://issuehunt.io/repos/256925027/issues/122)
---
</details>
=> Rename Tab now through Modal like search

package-lock.json, package.json, src/copy-mode/copymode-addon.ts, src/css/terminal7.css, src/gate.js, src/index.js, src/pane.js, src/terminal7.js, tsconfig.json, webpack.config.js, www/index.html
Adds copy mode
- Can be initiated by 
- cmd+[ 
- pressing enter in the search bar
- selecting text
- When active
- icon shows up
- arrows/hjkl change the selected text range
- '[' or space choose whether to change the beginning of the range or its end
- 'Enter' completes and copies selection to clipboard
- 'q' or 'Escape' completes without copying to clipboard
=> Copy mode - initial version

src/gate.ts
=> Fixing gate not opening on first click

css/terminal7.css, index.html, src/cell.js, src/pane.js
Simple folding animation for the search bar, closes #246.
=> Adding search box animation

css/terminal7.css, index.html, src/commands.ts, src/form.ts, src/gate.ts, src/shell.ts, src/terminal7.js, tests/infra.ts
Lots of small additions:
Resolves #307 (not all features implemented, still thinking on how it should be done).
Resolves #298.
Resolves #218.
Resolves #304.
=> t7sh Enchancements

src/pane.js
=> Fixing extra newline added at the end of copied text

src/commands.ts, src/gate.ts, src/session.ts, src/shell.ts
=> Saving gate address after a failed connection

src/terminal7.js
Resolves #322.
Couldn't check if it actually functions since I'm on PC but on reload the gate seems to remember the setting.
=> Fixing ssh only not saved

css/terminal7.css, src/map.ts
Fixes #306.
I hope the ResizeObserver works on the iPad.
=> Fixing TWR in narrow screens

css/terminal7.css, src/terminal7.js
=> Fixing the changelog

src/shell.ts
Resolves #339.
We may want to implement tab completion as well, let me know what you think.
=> Adding completion for gate names

src/commands.ts, src/gate.ts, src/map.ts, src/terminal7.js
=> Fixing Peerbook gates

.editorconfig, src/shell.ts
Resolves #363.
Simple implementation, should be fully working.
=> Adding support for TWR history

src/commands.ts, src/shell.ts
Resolves #354. Resolves #369. Resolves #370.
Hopefully resolves #371.
=> Moving subscribe to gate failure

.github/workflows/test.yml, .github/workflows/validate.yml, aatp/http_webrtc/lab.yaml, aatp/infra/peerbook/Dockerfile, aatp/peerbook_webrtc/lab.yaml, src/commands.ts
Fixed the linting errors and the acceptance tests.
=> Fixing GitHub Workflow

src/commands.ts
Resolves #380.
Also sorted the commands alphabetically.
=> Adding support command

ios/App/App.xcodeproj/project.pbxproj, src/commands.ts, src/gate.ts, src/map.ts, src/peerbook.ts, src/shell.ts, src/terminal7.js
- Updating xcode conf
- Fixing peerbook subscribe and install
=> Fixing peerbook

__mocks__/xterm.ts, src/pane.js
=> Fixing search

src/commands.ts
=> Refactoring gates cmd

css/terminal7.css, index.html, main.js, src/gate.ts, src/map.ts, src/webrtc_session.ts
Resolves #141. Stats are shown on the gate pad and inside the gate itself.
=> Adding stats to webrtc connections
